---
name: Renovate

"on":
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub App Token
        id: get_token
        # yamllint disable-line rule:line-length
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        with:
          app-id: ${{ vars.RENOVATE_BOT_APP_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Self-hosted Renovate
        # yamllint disable-line rule:line-length
        uses: renovatebot/github-action@66387ab8c2464d575b933fa44e9e5a86b2822809 # v44.2.4
        env:
          LOG_LEVEL: debug
          RENOVATE_TOKEN: ${{ steps.get_token.outputs.token }}
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
