---
name: Renovate

"on":
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub App Token
        id: get_token
        # yamllint disable-line rule:line-length
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
        with:
          app-id: ${{ vars.RENOVATE_BOT_APP_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Self-hosted Renovate
        # yamllint disable-line rule:line-length
        uses: renovatebot/github-action@c91a61c730fa166439cd3e2c300c041590002b1d # v44.0.3
        env:
          LOG_LEVEL: debug
          RENOVATE_TOKEN: ${{ steps.get_token.outputs.token }}
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
